font = "Consolas"
font_size = 13.0
theme = "gruvbox_dark"

[language.rust]
extensions = ["rs"]
indent_width = 4

[language.rust.syntax]
keywords = [
    "as",
    "break",
    "const",
    "continue",
    "crate",
    "else",
    "enum",
    "extern",
    "false",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "Self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", escape = '\', max_length = 1, kind = "String" },
    { start = "#[", end = "]", kind = "Preprocessor" },
    { start = "#![", end = "]", kind = "Preprocessor" },
    { start = "//", end = "\n", kind = "Comment" },
    { start = "/*", end = "*/", kind = "Comment" },
]

[language.toml]
extensions = ["toml"]
indent_width = 4
comment = "#"

[language.toml.syntax]
keywords = [
    "true",
    "false",
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", kind = "String" },
    { start = "#", end = "\n", kind = "Comment" },
]

[language.js]
extensions = ["js"]
indent_width = 4

[language.js.syntax]
keywords = [
    "abstract",
    "arguments",
    "await",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "double",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "final",
    "finally",
    "float",
    "for",
    "function",
    "goto",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "int",
    "interface",
    "let",
    "long",
    "native",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "volatile",
    "while",
    "with",
    "yield",
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", escape = '\', kind = "String" },
    { start = "`", end = "`", escape = '\', kind = "String" },
    { start = "//", end = "\n", kind = "Comment" },
    { start = "/*", end = "*/", kind = "Comment" },
]
