normal = "000000FF"
comment = "008000FF"
keyword = "0000FFFF"
function = "795E26FF"
number = "098658FF"
symbol = "000000FF"
string = "A31515FF"
preprocessor = "AF00DBFF"
selection = "4CADE47F"
line_number = "6E7681FF"
border = "E5E5E5FF"
background = "F5F5F5FF"
