normal = "CCCCCCFF"
comment = "6A9955FF"
keyword = "569CD6FF"
function = "DCDCAAFF"
number = "B5CEA8FF"
symbol = "CCCCCCFF"
string = "CE9178FF"
preprocessor = "C586C0FF"
selection = "4CADE47F"
line_number = "6E7681FF"
border = "2B2B2BFF"
background = "1E1E1EFF"
