normal = "FDF4C1"
identifier = "83A598"
comment = "7C6F64"
keyword = "DD6F48"
function = "A89984"
number = "D3869B"
symbol = "FDF4C1"
string = "528B8B"
meta = "DD6F48"
selection = "1B5C6B7F"
line_number = "7C6F64"
border = "383838"
background = "282828"
warning = "C5A82D"
error = "AB311F"
