normal = "000000"
identifier = "001080"
comment = "008000"
keyword = "0000FF"
function = "795E26"
number = "098658"
symbol = "000000"
string = "A31515"
meta = "AF00DB"
selection = "4CADE47F"
line_number = "6E7681"
border = "E5E5E5"
background = "F5F5F5"

[terminal]
foreground = "2A2C33"
background = "F5F5F5"
red = "DE3E35"
green = "3F953A"
yellow = "D2B67C"
blue = "2F5AF3"
magenta = "950095"
cyan = "3F953A"
bright_foreground = "000000"
bright_background = "BBBBBB"
bright_red = "DE3E35"
bright_green = "3F953A"
bright_yellow = "D2B67C"
bright_blue = "2F5AF3"
bright_magenta = "A00095"
bright_cyan = "3F953A"
