normal = "CCCCCC"
identifier = "9CDCFE"
comment = "6A9955"
keyword = "569CD6"
function = "DCDCAA"
number = "B5CEA8"
symbol = "CCCCCC"
string = "CE9178"
meta = "C586C0"
selection = "4CADE47F"
line_number = "6E7681"
border = "2B2B2B"
background = "1E1E1E"
warning = "C5A82D"
error = "AB311F"
