normal = "383A42"
identifier = "383A42"
comment = "A0A1A7"
keyword = "A626A4"
function = "4078F2"
number = "986801"
symbol = "383A42"
string = "50A14F"
meta = "986801"
selection = "4CADE47F"
line_number = "9D9D9F"
border = "E5E5E5"
background = "FAFAFA"
warning = "B58A26"
error = "EA695D"

[terminal]
foreground = "2A2C33"
background = "F9F9F9"
red = "DE3E35"
green = "3F953A"
yellow = "D2B67C"
blue = "2F5AF3"
magenta = "950095"
cyan = "3F953A"
bright_foreground = "000000"
bright_background = "BBBBBB"
bright_red = "DE3E35"
bright_green = "3F953A"
bright_yellow = "D2B67C"
bright_blue = "2F5AF3"
bright_magenta = "A00095"
bright_cyan = "3F953A"
