extensions = ["c"]
indent_width = 4

[syntax]
keywords = [
    "alignas",
    "alignof",
    "auto",
    "bool",
    "break",
    "case",
    "char",
    "const",
    "constexpr",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "false",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "nullptr",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "struct",
    "switch",
    "thread_local",
    "true",
    "typedef",
    "typeof",
    "typeof_unqual",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", escape = '\', max_length = 1, kind = "String" },
    { start = "#", end = "\n", kind = "Preprocessor" },
    { start = "//", end = "\n", kind = "Comment" },
    { start = "/*", end = "*/", kind = "Comment" },
]
