extensions = ["html", "xml"]
indent_width = 4

[syntax]
prefixes = { "<" = "Keyword", "</" = "Keyword", "<!" = "Keyword" }
ranges = [
    { start = '"', end = '"', kind = "String" },
    { start = "<!--", end = "-->", kind = "Comment" },
]
