extensions = ["html", "xml"]
indent_width = 4

[syntax]
tokens = [
    { pattern = "<(%w+)", kind = "Keyword" },
    { pattern = "</(%w+)", kind = "Keyword" },
    { pattern = "<!(%w+)", kind = "Keyword" },
]
ranges = [
    { start = '"', end = '"', kind = "String" },
    { start = "<!%-%-", end = "%-%->", kind = "Comment" },
]
