extensions = ["js"]
indent_width = 4

[syntax]
keywords = [
    "arguments",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
]
tokens = [
    { pattern = "//%.*", kind = "Comment" },
    { pattern = "([%a_][%w_]*)%(", kind = "Function" },
    { pattern = "0x%x*", kind = "Number" },
    { pattern = "0b[01]*", kind = "Number" },
    { pattern = "%d[%d_.]*", kind = "Number" },
    { pattern = "[!=&,><./:@^|;{}()%%%*%+%-%?%[%]]", kind = "Symbol" },
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", escape = '\', kind = "String" },
    { start = "`", end = "`", escape = '\', kind = "String" },
    { start = '/%*', end = '%*/', kind = "Comment" },
]
