extensions = ["toml"]
indent_width = 4
comment = "#"

[syntax]
keywords = ["true", "false"]
tokens = [{ pattern = "#%.*", kind = "Comment" }]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", kind = "String" },
]
