extensions = ["c"]
indent_width = 4

[syntax]
keywords = [
    "alignas",
    "alignof",
    "auto",
    "bool",
    "break",
    "case",
    "char",
    "const",
    "constexpr",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "false",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "nullptr",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "struct",
    "switch",
    "thread_local",
    "true",
    "typedef",
    "typeof",
    "typeof_unqual",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
]
tokens = [
    { pattern = "//%.*", kind = "Comment" },
    { pattern = "#%.*", kind = "Meta" },
    { pattern = "([%a_][%w_]*)%(", kind = "Function" },
    { pattern = "0x%x+", kind = "Number" },
    { pattern = "(%d+.?%d*)[^.]", kind = "Number" },
    { pattern = "%d+", kind = "Number" },
    { pattern = "[!=&,><./:@^|;{}()%%%*%+%-%?%[%]]", kind = "Symbol" },
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", escape = '\', kind = "String" },
    { start = "`", end = "`", escape = '\', kind = "String" },
    { start = '/%*', end = '%*/', kind = "Comment" },
]
