extensions = ["rs"]
indent_width = 4
language_server_command = "rust-analyzer"

[syntax]
keywords = [
    "as",
    "break",
    "const",
    "continue",
    "crate",
    "else",
    "enum",
    "extern",
    "false",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "Self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
]
tokens = [
    { pattern = "//%.*", kind = "Comment" },
    { pattern = "[%a_][%w_]*!", kind = "Meta" },
    { pattern = "([%a_][%w_]*)%s*%(", kind = "Function" },
    { pattern = "([%a_][%w_]*)%s*<%.->%s*%(", kind = "Function" },
    { pattern = "([%a_][%w_]*)%s*::%s*<%.->%s*%(", kind = "Function" },
    { pattern = "0x%x+", kind = "Number" },
    { pattern = "0b[01]+", kind = "Number" },
    { pattern = "(%d[%d_]*.?[%d_]*)[^.]", kind = "Number" },
    { pattern = "%d[%d_]*", kind = "Number" },
    { pattern = "'\\u{%x-}'", kind = "String" },
    { pattern = "'\\?%.'", kind = "String" },
    { pattern = "'%l+", kind = "Meta" },
    { pattern = "[!=&,><./:@|;{}()%%%^%*%+%-%?%[%]]", kind = "Symbol" },
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = 'r#*"', end = '"#*', kind = "String" },
    { start = '#%[', end = '%]', kind = "Meta" },
    { start = '#!%[', end = '%]', kind = "Meta" },
    { start = '/%*', end = '%*/', kind = "Comment" },
]
