extensions = ["toml"]
indent_width = 4
comment = "#"

[syntax]
keywords = ["true", "false"]
tokens = [
    { pattern = "#%.*", kind = "Comment" },
    { pattern = "0x%x+", kind = "Number" },
    { pattern = "0b[01]+", kind = "Number" },
    { pattern = "(%d[%d_]*.?[%d_]*)[^.]", kind = "Number" },
    { pattern = "%d[%d_]*", kind = "Number" },
]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", kind = "String" },
]
