extensions = ["toml"]
indent_width = 4
comment = "#"

[syntax]
keywords = ["true", "false"]
ranges = [
    { start = '"', end = '"', escape = '\', kind = "String" },
    { start = "'", end = "'", kind = "String" },
    { start = "#", end = "\n", kind = "Comment" },
]
