normal = "CCCCCC"
comment = "6A9955"
keyword = "569CD6"
function = "DCDCAA"
number = "B5CEA8"
symbol = "CCCCCC"
string = "CE9178"
preprocessor = "C586C0"
selection = "4CADE47F"
line_number = "6E7681"
border = "2B2B2B"
background = "1E1E1E"
