normal = "000000"
comment = "008000"
keyword = "0000FF"
function = "795E26"
number = "098658"
symbol = "000000"
string = "A31515"
meta = "AF00DB"
selection = "4CADE47F"
line_number = "6E7681"
border = "E5E5E5"
background = "F5F5F5"
