normal = "EBDBB2"
comment = "665C54"
keyword = "FB4934"
function = "B8BB26"
number = "D3869B"
symbol = "EBDBB2"
string = "B8BB26"
meta = "689D6A"
selection = "4CADE47F"
line_number = "665C54"
border = "3C3836"
background = "282828"

[terminal]
foreground = "FBF1C7"
background = "1D2021"
blue = "458588"
cyan = "689D6A"
green = "98971A"
magenta = "B16286"
red = "CC241D"
yellow = "D79921"
bright_foreground = "F9F5D7"
bright_background = "928374"
bright_blue = "83A598"
bright_cyan = "8EC07C"
bright_green = "B8BB26"
bright_magenta = "D3869B"
bright_red = "FB4934"
bright_yellow = "FABD2F"
