normal = "EBDBB2"
comment = "665C54"
keyword = "FB4934"
function = "B8BB26"
number = "D3869B"
symbol = "EBDBB2"
string = "B8BB26"
preprocessor = "689D6A"
selection = "4CADE47F"
line_number = "665C54"
border = "3C3836"
background = "282828"
