mod camera;
pub mod color;
pub mod command_palette;
pub mod controller;
pub mod core;
pub mod editor;
pub mod msg;
mod pane;
mod pane_list;
mod popup;
mod result_list;
mod slot_list;
pub mod status_bar;
pub mod tab;
pub mod terminal;
